---
# chrony tasks/Debian.yml
#
# SPDX-FileCopyrightText: © 2021 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Install chrony packages
  apt:
    name:
      - chrony
    update_cache: true
    cache_valid_time: 3600
  notify:
    - start-chrony
