---
# chrony molecule/default/verify.yml
#
# SPDX-FileCopyrightText: © 2021 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Converge
  hosts: all
  tasks:
    - name: "Include chrony"
      include_role:
        name: "chrony"
